Language select option and clean template from old browsers
jaketrent/html-webpack-template pull request #35
Opened 2016-10-27 19:29 UTC by azat-io

Hello!

* Added language select option because your package can be useful by people from another counties.
* Removed trash tags for an old IE browsers. This browsers currently using by less than 1% of people around the world ([proof](http://browserl.ist/?q=%3E+1%25))

Please merge pull request and create new release of your package :smiley:

2016-10-27 20:00 UTC, jaketrent commented on index.ejs
> +<html<% if (htmlWebpackPlugin.files.lang) { %> lang="<%= htmlWebpackPlugin.options.lang %>"<% } %>>
Good idea.  Please add a default above to 'en'.  Also looks like you removed the manifest support.  Will you add that back, please?

2016-10-27 20:44 UTC, azat-io commented
@jaketrent :+1: 
* Back manifest
* Select English as default language

2016-10-28 15:08 UTC, jaketrent requested changes

2016-10-28 15:08 UTC, jaketrent commented on index.ejs
> +<% if (htmlWebpackPlugin.files.lang) { %> lang="<%= htmlWebpackPlugin.options.lang %>"<% } %><% else { %> lang="en"<% } %><% if (htmlWebpackPlugin.files.manifest)<% if (htmlWebpackPlugin.files.manife
@azat-io , I think this default will work, but I wonder if you wouldn't mind using the strategy we've used for defaults thus far instead.  For instance, see line 6:

```
<% htmlWebpackPlugin.options.scripts = htmlWebpackPlugin.options.scripts || [] %>
```

Something like that at the top of the file would be nice.  Then you could avoid the else branch inline.  Sound ok?

2017-02-17 19:03 UTC, godart reviewed
I like the idea of dropping this legacy support.

Is there a way this can be merged without the rest (which seems abandoned to me)?

2017-04-20 15:09 UTC, TAGC commented
+1 for removing trash tags.

2017-04-25 06:08 UTC, rodmoreno commented
What happened to this PR? I would love to have the support to choose the language

2017-05-04 12:49 UTC, jaketrent commented
I would like to get this included.  Looks like we have a couple file conflicts at this point.  For some reason, github doesn't know what branch this is on.  The changes are small enough, I could recreate.  @azat-io any input on how you'd like this to proceed, resolving conflicts?  Thanks.

2017-07-11 12:39 UTC, jaketrent commented
Reimplemented in 49ea502.

2017-07-11 12:39 UTC, closed without merging

2017-07-11 12:41 UTC, jaketrent commented
Published in 5.6.0